/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zd17001.parábola;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import static zd17001.parábola.Menu.escritorio;

/**
 *
 * @author jose_
 */
public class newFile extends javax.swing.JInternalFrame {

   
    Color color1 = new java.awt.Color(101, 52, 172);
    Color color2 = new java.awt.Color(45, 54, 76);

    /**
     * Creates new form newFile
     */
    public newFile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCerrar = new keeptoo.KButton();
        btnTrazo = new keeptoo.KButton();
        btnArtBoard = new keeptoo.KButton();
        btnCrear = new keeptoo.KButton();
        jLabel1 = new javax.swing.JLabel();
        combo = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new jtextfieldround.JTextFieldRound();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(45, 54, 76));
        jPanel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnCerrar.setText("Salir");
        btnCerrar.setBorderPainted(false);
        btnCerrar.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        btnCerrar.setkAllowGradient(false);
        btnCerrar.setkBackGroundColor(new java.awt.Color(101, 52, 172));
        btnCerrar.setkBorderRadius(40);
        btnCerrar.setkHoverForeGround(new java.awt.Color(101, 52, 172));
        btnCerrar.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 280, 118, -1));

        btnTrazo.setText("Trazo");
        btnTrazo.setToolTipText("Color de trazo");
        btnTrazo.setBorderPainted(false);
        btnTrazo.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        btnTrazo.setkAllowGradient(false);
        btnTrazo.setkBackGroundColor(new java.awt.Color(101, 52, 172));
        btnTrazo.setkBorderRadius(40);
        btnTrazo.setkHoverForeGround(new java.awt.Color(101, 52, 172));
        btnTrazo.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        btnTrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrazoActionPerformed(evt);
            }
        });
        jPanel1.add(btnTrazo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        btnArtBoard.setText("Área de trabajo");
        btnArtBoard.setToolTipText("Color de área de trabajo");
        btnArtBoard.setBorderPainted(false);
        btnArtBoard.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        btnArtBoard.setkAllowGradient(false);
        btnArtBoard.setkBackGroundColor(new java.awt.Color(101, 52, 172));
        btnArtBoard.setkBorderRadius(40);
        btnArtBoard.setkHoverForeGround(new java.awt.Color(101, 52, 172));
        btnArtBoard.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        btnArtBoard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnArtBoardActionPerformed(evt);
            }
        });
        jPanel1.add(btnArtBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, -1, -1));

        btnCrear.setText("Crear");
        btnCrear.setBorderPainted(false);
        btnCrear.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        btnCrear.setkAllowGradient(false);
        btnCrear.setkBackGroundColor(new java.awt.Color(12, 183, 84));
        btnCrear.setkBorderRadius(40);
        btnCrear.setkHoverForeGround(new java.awt.Color(12, 183, 84));
        btnCrear.setkHoverStartColor(new java.awt.Color(255, 255, 255));
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });
        jPanel1.add(btnCrear, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 280, 118, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Figura");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 170, 130, 34));

        combo.setBackground(new java.awt.Color(101, 52, 172));
        combo.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Parábola", "Círculo", "Elipse", "Línea" }));
        jPanel1.add(combo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 110, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Microsoft Tai Le", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("¡Bienvenido al programa de Algoritmos Gráficos!");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 740, 34));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/adobe_after_effects_127px.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 120, 120));

        txtNombre.setText("Nombre archivo");
        txtNombre.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNombre.setFont(new java.awt.Font("Microsoft Tai Le", 1, 12)); // NOI18N
        txtNombre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNombreMouseClicked(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 270, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        if (!this.txtNombre.getText().isEmpty()) {
            String comboFig = combo.getSelectedItem().toString();
            String nombre = txtNombre.getText();

            this.dispose();
            ParabolaDibujar e = new ParabolaDibujar(color1, color2, comboFig, nombre);
            escritorio.add(e);
            Dimension dp = escritorio.getSize();
            Dimension dq = e.getSize();
            e.setLocation((dp.width - dq.width) / 2, (dp.height - dq.height) / 2);
            e.show();
        } else {

            JOptionPane.showMessageDialog(null, "Nombre vacío",
                    "", JOptionPane.PLAIN_MESSAGE, icono("/images/aviso.png", 70, 70));

        }
    }//GEN-LAST:event_btnCrearActionPerformed

    private Icon icono(String path, int width, int heigth) {
        Icon img = new ImageIcon(new ImageIcon(getClass().getResource(path)).getImage()
                .getScaledInstance(width, heigth, java.awt.Image.SCALE_SMOOTH));
        return img;
    }
    private void btnArtBoardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnArtBoardActionPerformed
        // TODO add your handling code here:
        JColorChooser ventanColor = new JColorChooser();
        color2 = ventanColor.showDialog(null, "Selecciona un color", new java.awt.Color(45, 54, 76));
        btnArtBoard.setkBackGroundColor(color2);
        btnArtBoard.setkHoverColor(color2);
        btnArtBoard.setkHoverForeGround(Color.WHITE);

    }//GEN-LAST:event_btnArtBoardActionPerformed

    private void btnTrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrazoActionPerformed
        JColorChooser ventanColor = new JColorChooser();
        color1 = ventanColor.showDialog(null, "Selecciona un color", new java.awt.Color(101, 52, 172));
        btnTrazo.setkBackGroundColor(color1);
        btnTrazo.setkHoverColor(color1);
        btnTrazo.setkHoverForeGround(Color.WHITE);
    }//GEN-LAST:event_btnTrazoActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void txtNombreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNombreMouseClicked
        this.txtNombre.setText(null);// TODO add your handling code here 
    }//GEN-LAST:event_txtNombreMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private keeptoo.KButton btnArtBoard;
    private keeptoo.KButton btnCerrar;
    private keeptoo.KButton btnCrear;
    private keeptoo.KButton btnTrazo;
    private javax.swing.JComboBox<String> combo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private jtextfieldround.JTextFieldRound txtNombre;
    // End of variables declaration//GEN-END:variables
}
